# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Ecommerce CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      - name: Setup Python for Backend
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

  gitLeaksScan:
    name: GitLeaks Scan
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cleanup temp gitleaks file
        run: 
          rm -f /tmp/gitleaks.tmp
          rm -rf /tmp/gitleaks-*

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2

      - name: Run Gitleaks
        run: gitleaks detect --source . --exit-code 1

  TrivyFileScan:
    name: Trivy File Scan
    runs-on: ubuntu-latest
    needs: gitLeaksScan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cleanup temp trivy file
        run: 
          rm -f /tmp/trivy.tmp
          rm -rf /tmp/trivy-*

      - name: Trivy File Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Show Trivy Scan Result
        if: failure()
        run: cat /tmp/trivy.tmp
          
  dockerBuild:
    name: Docker Build and Push with Trivy Scan
    runs-on: ubuntu-latest
    needs: TrivyFileScan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          load: true
          tags: kavindusamaranayake/ecommerce-app-backend:latest
          file: ./backend/Dockerfile

      - name: Run Trivy vulnerability scan for Backend Image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          image-ref: kavindusamaranayake/ecommerce-app-backend:latest
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          load: true
          tags: kavindusamaranayake/ecommerce-app-frontend:latest
          file: ./frontend/Dockerfile 

      - name: Run Trivy vulnerability scan for Frontend Image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          image-ref: kavindusamaranayake/ecommerce-app-frontend:latest
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
